trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ClinicWorks-IAC/**

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: "sc-clinicworks-azure"
  resourceGroupName: "rg-clinicworks-dev-ci"
  templateFile: "ClinicWorks-IAC/main.bicep"
  parameterFile: "ClinicWorks-IAC/parameters/dev.bicepparam"

stages:
  # ============================================================
  # Stage 1: Bicep Build
  # ============================================================
  - stage: Bicep_Build
    displayName: "Bicep Build"

    jobs:
      - job: Build
        displayName: "Build Bicep"

        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Build Bicep"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az bicep build \
                  --file $(templateFile)

  # ============================================================
  # Stage 2: Bicep Validate
  # ============================================================
  - stage: Bicep_Validate
    displayName: "Bicep Validate"
    dependsOn: Bicep_Build

    jobs:
      - job: Validate
        displayName: "Validate Bicep Deployment"

        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Validate Bicep"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group validate \
                  --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters $(parameterFile)

  # ============================================================
  # Stage 3: Bicep What-If
  # ============================================================
  - stage: Bicep_WhatIf
    displayName: "Bicep What-If"
    dependsOn: Bicep_Validate

    jobs:
      - job: WhatIf
        displayName: "Run Bicep What-If"

        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Bicep What-If"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group what-if \
                  --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters $(parameterFile)
